// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MarkovChain.proto

package de.cbruegg.mcl.proto;

public final class MarkovChainOuterClass {
  private MarkovChainOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MarkovChainOrBuilder extends
      // @@protoc_insertion_point(interface_extends:de.cbruegg.mcl.proto.MarkovChain)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string words = 1;</code>
     *
     * <pre>
     * All states in the chain
     * </pre>
     */
    com.google.protobuf.ProtocolStringList
        getWordsList();
    /**
     * <code>repeated string words = 1;</code>
     *
     * <pre>
     * All states in the chain
     * </pre>
     */
    int getWordsCount();
    /**
     * <code>repeated string words = 1;</code>
     *
     * <pre>
     * All states in the chain
     * </pre>
     */
    java.lang.String getWords(int index);
    /**
     * <code>repeated string words = 1;</code>
     *
     * <pre>
     * All states in the chain
     * </pre>
     */
    com.google.protobuf.ByteString
        getWordsBytes(int index);

    /**
     * <code>map&lt;string, .de.cbruegg.mcl.proto.TransitionsFrom&gt; transitions = 2;</code>
     *
     * <pre>
     * Transitions mapped by their beginning word
     * </pre>
     */
    java.util.Map<java.lang.String, de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom>
    getTransitions();
  }
  /**
   * Protobuf type {@code de.cbruegg.mcl.proto.MarkovChain}
   */
  public  static final class MarkovChain extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:de.cbruegg.mcl.proto.MarkovChain)
      MarkovChainOrBuilder {
    // Use MarkovChain.newBuilder() to construct.
    private MarkovChain(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MarkovChain() {
      words_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MarkovChain(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                words_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              words_.add(s);
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                transitions_ = com.google.protobuf.MapField.newMapField(
                    TransitionsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom>
              transitions = input.readMessage(
                  TransitionsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              transitions_.getMutableMap().put(transitions.getKey(), transitions.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          words_ = words_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.cbruegg.mcl.proto.MarkovChainOuterClass.internal_static_de_cbruegg_mcl_proto_MarkovChain_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetTransitions();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.cbruegg.mcl.proto.MarkovChainOuterClass.internal_static_de_cbruegg_mcl_proto_MarkovChain_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain.class, de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain.Builder.class);
    }

    public static final int WORDS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList words_;
    /**
     * <code>repeated string words = 1;</code>
     *
     * <pre>
     * All states in the chain
     * </pre>
     */
    public com.google.protobuf.ProtocolStringList
        getWordsList() {
      return words_;
    }
    /**
     * <code>repeated string words = 1;</code>
     *
     * <pre>
     * All states in the chain
     * </pre>
     */
    public int getWordsCount() {
      return words_.size();
    }
    /**
     * <code>repeated string words = 1;</code>
     *
     * <pre>
     * All states in the chain
     * </pre>
     */
    public java.lang.String getWords(int index) {
      return words_.get(index);
    }
    /**
     * <code>repeated string words = 1;</code>
     *
     * <pre>
     * All states in the chain
     * </pre>
     */
    public com.google.protobuf.ByteString
        getWordsBytes(int index) {
      return words_.getByteString(index);
    }

    public static final int TRANSITIONS_FIELD_NUMBER = 2;
    private static final class TransitionsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom>newDefaultInstance(
                  de.cbruegg.mcl.proto.MarkovChainOuterClass.internal_static_de_cbruegg_mcl_proto_MarkovChain_TransitionsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom> transitions_;
    private com.google.protobuf.MapField<java.lang.String, de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom>
    internalGetTransitions() {
      if (transitions_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TransitionsDefaultEntryHolder.defaultEntry);
     }
      return transitions_;
    }
    /**
     * <code>map&lt;string, .de.cbruegg.mcl.proto.TransitionsFrom&gt; transitions = 2;</code>
     *
     * <pre>
     * Transitions mapped by their beginning word
     * </pre>
     */

    public java.util.Map<java.lang.String, de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom> getTransitions() {
      return internalGetTransitions().getMap();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < words_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, words_.getRaw(i));
      }
      for (java.util.Map.Entry<java.lang.String, de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom> entry
           : internalGetTransitions().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom>
        transitions = TransitionsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(2, transitions);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < words_.size(); i++) {
          dataSize += computeStringSizeNoTag(words_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getWordsList().size();
      }
      for (java.util.Map.Entry<java.lang.String, de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom> entry
           : internalGetTransitions().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom>
        transitions = TransitionsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, transitions);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code de.cbruegg.mcl.proto.MarkovChain}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:de.cbruegg.mcl.proto.MarkovChain)
        de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChainOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.cbruegg.mcl.proto.MarkovChainOuterClass.internal_static_de_cbruegg_mcl_proto_MarkovChain_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetTransitions();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableTransitions();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.cbruegg.mcl.proto.MarkovChainOuterClass.internal_static_de_cbruegg_mcl_proto_MarkovChain_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain.class, de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain.Builder.class);
      }

      // Construct using de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        words_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableTransitions().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.cbruegg.mcl.proto.MarkovChainOuterClass.internal_static_de_cbruegg_mcl_proto_MarkovChain_descriptor;
      }

      public de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain getDefaultInstanceForType() {
        return de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain.getDefaultInstance();
      }

      public de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain build() {
        de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain buildPartial() {
        de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain result = new de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          words_ = words_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.words_ = words_;
        result.transitions_ = internalGetTransitions();
        result.transitions_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain) {
          return mergeFrom((de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain other) {
        if (other == de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain.getDefaultInstance()) return this;
        if (!other.words_.isEmpty()) {
          if (words_.isEmpty()) {
            words_ = other.words_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureWordsIsMutable();
            words_.addAll(other.words_);
          }
          onChanged();
        }
        internalGetMutableTransitions().mergeFrom(
            other.internalGetTransitions());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList words_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureWordsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          words_ = new com.google.protobuf.LazyStringArrayList(words_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string words = 1;</code>
       *
       * <pre>
       * All states in the chain
       * </pre>
       */
      public com.google.protobuf.ProtocolStringList
          getWordsList() {
        return words_.getUnmodifiableView();
      }
      /**
       * <code>repeated string words = 1;</code>
       *
       * <pre>
       * All states in the chain
       * </pre>
       */
      public int getWordsCount() {
        return words_.size();
      }
      /**
       * <code>repeated string words = 1;</code>
       *
       * <pre>
       * All states in the chain
       * </pre>
       */
      public java.lang.String getWords(int index) {
        return words_.get(index);
      }
      /**
       * <code>repeated string words = 1;</code>
       *
       * <pre>
       * All states in the chain
       * </pre>
       */
      public com.google.protobuf.ByteString
          getWordsBytes(int index) {
        return words_.getByteString(index);
      }
      /**
       * <code>repeated string words = 1;</code>
       *
       * <pre>
       * All states in the chain
       * </pre>
       */
      public Builder setWords(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureWordsIsMutable();
        words_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string words = 1;</code>
       *
       * <pre>
       * All states in the chain
       * </pre>
       */
      public Builder addWords(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureWordsIsMutable();
        words_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string words = 1;</code>
       *
       * <pre>
       * All states in the chain
       * </pre>
       */
      public Builder addAllWords(
          java.lang.Iterable<java.lang.String> values) {
        ensureWordsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, words_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string words = 1;</code>
       *
       * <pre>
       * All states in the chain
       * </pre>
       */
      public Builder clearWords() {
        words_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string words = 1;</code>
       *
       * <pre>
       * All states in the chain
       * </pre>
       */
      public Builder addWordsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureWordsIsMutable();
        words_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom> transitions_;
      private com.google.protobuf.MapField<java.lang.String, de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom>
      internalGetTransitions() {
        if (transitions_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              TransitionsDefaultEntryHolder.defaultEntry);
       }
        return transitions_;
      }
      private com.google.protobuf.MapField<java.lang.String, de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom>
      internalGetMutableTransitions() {
        onChanged();;
        if (transitions_ == null) {
          transitions_ = com.google.protobuf.MapField.newMapField(
              TransitionsDefaultEntryHolder.defaultEntry);
        }
        if (!transitions_.isMutable()) {
          transitions_ = transitions_.copy();
        }
        return transitions_;
      }
      /**
       * <code>map&lt;string, .de.cbruegg.mcl.proto.TransitionsFrom&gt; transitions = 2;</code>
       *
       * <pre>
       * Transitions mapped by their beginning word
       * </pre>
       */
      public java.util.Map<java.lang.String, de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom> getTransitions() {
        return internalGetTransitions().getMap();
      }
      /**
       * <code>map&lt;string, .de.cbruegg.mcl.proto.TransitionsFrom&gt; transitions = 2;</code>
       *
       * <pre>
       * Transitions mapped by their beginning word
       * </pre>
       */
      public java.util.Map<java.lang.String, de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom>
      getMutableTransitions() {
        return internalGetMutableTransitions().getMutableMap();
      }
      /**
       * <code>map&lt;string, .de.cbruegg.mcl.proto.TransitionsFrom&gt; transitions = 2;</code>
       *
       * <pre>
       * Transitions mapped by their beginning word
       * </pre>
       */
      public Builder putAllTransitions(
          java.util.Map<java.lang.String, de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom> values) {
        getMutableTransitions().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:de.cbruegg.mcl.proto.MarkovChain)
    }

    // @@protoc_insertion_point(class_scope:de.cbruegg.mcl.proto.MarkovChain)
    private static final de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain();
    }

    public static de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MarkovChain>
        PARSER = new com.google.protobuf.AbstractParser<MarkovChain>() {
      public MarkovChain parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new MarkovChain(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<MarkovChain> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MarkovChain> getParserForType() {
      return PARSER;
    }

    public de.cbruegg.mcl.proto.MarkovChainOuterClass.MarkovChain getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TransitionsFromOrBuilder extends
      // @@protoc_insertion_point(interface_extends:de.cbruegg.mcl.proto.TransitionsFrom)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, double&gt; probabilitiesByState = 1;</code>
     *
     * <pre>
     * End of the transition + probability of it
     * </pre>
     */
    java.util.Map<java.lang.String, java.lang.Double>
    getProbabilitiesByState();
  }
  /**
   * Protobuf type {@code de.cbruegg.mcl.proto.TransitionsFrom}
   */
  public  static final class TransitionsFrom extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:de.cbruegg.mcl.proto.TransitionsFrom)
      TransitionsFromOrBuilder {
    // Use TransitionsFrom.newBuilder() to construct.
    private TransitionsFrom(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TransitionsFrom() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TransitionsFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                probabilitiesByState_ = com.google.protobuf.MapField.newMapField(
                    ProbabilitiesByStateDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Double>
              probabilitiesByState = input.readMessage(
                  ProbabilitiesByStateDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              probabilitiesByState_.getMutableMap().put(probabilitiesByState.getKey(), probabilitiesByState.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.cbruegg.mcl.proto.MarkovChainOuterClass.internal_static_de_cbruegg_mcl_proto_TransitionsFrom_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetProbabilitiesByState();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.cbruegg.mcl.proto.MarkovChainOuterClass.internal_static_de_cbruegg_mcl_proto_TransitionsFrom_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom.class, de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom.Builder.class);
    }

    public static final int PROBABILITIESBYSTATE_FIELD_NUMBER = 1;
    private static final class ProbabilitiesByStateDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Double> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Double>newDefaultInstance(
                  de.cbruegg.mcl.proto.MarkovChainOuterClass.internal_static_de_cbruegg_mcl_proto_TransitionsFrom_ProbabilitiesByStateEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.DOUBLE,
                  0D);
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Double> probabilitiesByState_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
    internalGetProbabilitiesByState() {
      if (probabilitiesByState_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ProbabilitiesByStateDefaultEntryHolder.defaultEntry);
     }
      return probabilitiesByState_;
    }
    /**
     * <code>map&lt;string, double&gt; probabilitiesByState = 1;</code>
     *
     * <pre>
     * End of the transition + probability of it
     * </pre>
     */

    public java.util.Map<java.lang.String, java.lang.Double> getProbabilitiesByState() {
      return internalGetProbabilitiesByState().getMap();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (java.util.Map.Entry<java.lang.String, java.lang.Double> entry
           : internalGetProbabilitiesByState().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Double>
        probabilitiesByState = ProbabilitiesByStateDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(1, probabilitiesByState);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.Double> entry
           : internalGetProbabilitiesByState().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Double>
        probabilitiesByState = ProbabilitiesByStateDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, probabilitiesByState);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code de.cbruegg.mcl.proto.TransitionsFrom}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:de.cbruegg.mcl.proto.TransitionsFrom)
        de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFromOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.cbruegg.mcl.proto.MarkovChainOuterClass.internal_static_de_cbruegg_mcl_proto_TransitionsFrom_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetProbabilitiesByState();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableProbabilitiesByState();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.cbruegg.mcl.proto.MarkovChainOuterClass.internal_static_de_cbruegg_mcl_proto_TransitionsFrom_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom.class, de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom.Builder.class);
      }

      // Construct using de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableProbabilitiesByState().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.cbruegg.mcl.proto.MarkovChainOuterClass.internal_static_de_cbruegg_mcl_proto_TransitionsFrom_descriptor;
      }

      public de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom getDefaultInstanceForType() {
        return de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom.getDefaultInstance();
      }

      public de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom build() {
        de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom buildPartial() {
        de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom result = new de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom(this);
        int from_bitField0_ = bitField0_;
        result.probabilitiesByState_ = internalGetProbabilitiesByState();
        result.probabilitiesByState_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom) {
          return mergeFrom((de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom other) {
        if (other == de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom.getDefaultInstance()) return this;
        internalGetMutableProbabilitiesByState().mergeFrom(
            other.internalGetProbabilitiesByState());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Double> probabilitiesByState_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
      internalGetProbabilitiesByState() {
        if (probabilitiesByState_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ProbabilitiesByStateDefaultEntryHolder.defaultEntry);
       }
        return probabilitiesByState_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
      internalGetMutableProbabilitiesByState() {
        onChanged();;
        if (probabilitiesByState_ == null) {
          probabilitiesByState_ = com.google.protobuf.MapField.newMapField(
              ProbabilitiesByStateDefaultEntryHolder.defaultEntry);
        }
        if (!probabilitiesByState_.isMutable()) {
          probabilitiesByState_ = probabilitiesByState_.copy();
        }
        return probabilitiesByState_;
      }
      /**
       * <code>map&lt;string, double&gt; probabilitiesByState = 1;</code>
       *
       * <pre>
       * End of the transition + probability of it
       * </pre>
       */
      public java.util.Map<java.lang.String, java.lang.Double> getProbabilitiesByState() {
        return internalGetProbabilitiesByState().getMap();
      }
      /**
       * <code>map&lt;string, double&gt; probabilitiesByState = 1;</code>
       *
       * <pre>
       * End of the transition + probability of it
       * </pre>
       */
      public java.util.Map<java.lang.String, java.lang.Double>
      getMutableProbabilitiesByState() {
        return internalGetMutableProbabilitiesByState().getMutableMap();
      }
      /**
       * <code>map&lt;string, double&gt; probabilitiesByState = 1;</code>
       *
       * <pre>
       * End of the transition + probability of it
       * </pre>
       */
      public Builder putAllProbabilitiesByState(
          java.util.Map<java.lang.String, java.lang.Double> values) {
        getMutableProbabilitiesByState().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:de.cbruegg.mcl.proto.TransitionsFrom)
    }

    // @@protoc_insertion_point(class_scope:de.cbruegg.mcl.proto.TransitionsFrom)
    private static final de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom();
    }

    public static de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransitionsFrom>
        PARSER = new com.google.protobuf.AbstractParser<TransitionsFrom>() {
      public TransitionsFrom parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new TransitionsFrom(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<TransitionsFrom> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransitionsFrom> getParserForType() {
      return PARSER;
    }

    public de.cbruegg.mcl.proto.MarkovChainOuterClass.TransitionsFrom getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_cbruegg_mcl_proto_MarkovChain_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_cbruegg_mcl_proto_MarkovChain_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_cbruegg_mcl_proto_MarkovChain_TransitionsEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_cbruegg_mcl_proto_MarkovChain_TransitionsEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_cbruegg_mcl_proto_TransitionsFrom_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_cbruegg_mcl_proto_TransitionsFrom_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_cbruegg_mcl_proto_TransitionsFrom_ProbabilitiesByStateEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_cbruegg_mcl_proto_TransitionsFrom_ProbabilitiesByStateEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MarkovChain.proto\022\024de.cbruegg.mcl.prot" +
      "o\"\300\001\n\013MarkovChain\022\r\n\005words\030\001 \003(\t\022G\n\013tran" +
      "sitions\030\002 \003(\01322.de.cbruegg.mcl.proto.Mar" +
      "kovChain.TransitionsEntry\032Y\n\020Transitions" +
      "Entry\022\013\n\003key\030\001 \001(\t\0224\n\005value\030\002 \001(\0132%.de.c" +
      "bruegg.mcl.proto.TransitionsFrom:\0028\001\"\255\001\n" +
      "\017TransitionsFrom\022]\n\024probabilitiesByState" +
      "\030\001 \003(\0132?.de.cbruegg.mcl.proto.Transition" +
      "sFrom.ProbabilitiesByStateEntry\032;\n\031Proba" +
      "bilitiesByStateEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005val",
      "ue\030\002 \001(\001:\0028\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_de_cbruegg_mcl_proto_MarkovChain_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_de_cbruegg_mcl_proto_MarkovChain_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_de_cbruegg_mcl_proto_MarkovChain_descriptor,
        new java.lang.String[] { "Words", "Transitions", });
    internal_static_de_cbruegg_mcl_proto_MarkovChain_TransitionsEntry_descriptor =
      internal_static_de_cbruegg_mcl_proto_MarkovChain_descriptor.getNestedTypes().get(0);
    internal_static_de_cbruegg_mcl_proto_MarkovChain_TransitionsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_de_cbruegg_mcl_proto_MarkovChain_TransitionsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_de_cbruegg_mcl_proto_TransitionsFrom_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_de_cbruegg_mcl_proto_TransitionsFrom_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_de_cbruegg_mcl_proto_TransitionsFrom_descriptor,
        new java.lang.String[] { "ProbabilitiesByState", });
    internal_static_de_cbruegg_mcl_proto_TransitionsFrom_ProbabilitiesByStateEntry_descriptor =
      internal_static_de_cbruegg_mcl_proto_TransitionsFrom_descriptor.getNestedTypes().get(0);
    internal_static_de_cbruegg_mcl_proto_TransitionsFrom_ProbabilitiesByStateEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_de_cbruegg_mcl_proto_TransitionsFrom_ProbabilitiesByStateEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
